version: "3.8"

services:
  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    networks:
      - frontend
      - backend
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    networks:
      - backend
      - db
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - db

volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "!!!!"

networks:
  frontend:
  backend:
  db:
